export const products = [
  {
    slug: "amberpurple-arrowhead",
    name: "AmberPurple Arrowhead",
    nameDe: "AmberPurple Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€80",
    priceDe: "€80",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/amber-purple-arrowhead-1.webp",
    images: [
      "/jewelry/amber-purple-arrowhead-1.webp",
      "/jewelry/amber-purple-arrowhead-2.webp",
      "/jewelry/amber-purple-arrowhead-3.webp",
      "/jewelry/amber-purple-arrowhead-4.webp",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Amber and purple tones",
    colorsDe: "Amber- und Violetttöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description:
      "Handmade borosilicate glass pendant with an open arrowhead-inspired shape in amber and purple tones.",
    descriptionDe:
      "Handgemachter Anhänger aus Borosilikatglas mit offener, pfeilspitzenähnlicher Form in Amber- und Violetttönen.",
    story:
      "Made individually at the torch. The open structure and layered colors change noticeably with the light.",
    storyDe:
      "Einzeln am Brenner gefertigt. Die offene Struktur und die geschichteten Farben verändern ihre Wirkung deutlich mit dem Licht.",
  },
  {
    slug: "facetted-suncatcher",
    name: "Facetted Suncatcher",
    nameDe: "Facetted Suncatcher",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "Price on request",
    priceDe: "Preis auf Anfrage",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/facetted-suncatcher-1.webp",
    images: [
      "/jewelry/facetted-suncatcher-1.webp",
      "/jewelry/facetted-suncatcher-2.webp",
      "/jewelry/facetted-suncatcher-3.webp",
      "/jewelry/facetted-suncatcher-4.webp",
      "/jewelry/facetted-suncatcher-5.webp",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with warm reflections",
    colorsDe: "Klares Glas mit warmen Reflexionen",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description:
      "Handmade faceted borosilicate pendant with a small flower detail inside.",
    descriptionDe:
      "Handgemachter facettierter Anhänger aus Borosilikatglas mit einem kleinen Blütendetail im Inneren.",
    story:
      "The faceted surface changes the reflections depending on the light and viewing angle.",
    storyDe:
      "Die facettierte Oberfläche verändert die Reflexionen je nach Licht und Blickwinkel.",
  },
  {
    slug: "flower-implosion",
    name: "FlowerImplosion",
    nameDe: "FlowerImplosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€65",
    priceDe: "€65",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/flower-implosion-1.webp",
    images: [
      "/jewelry/flower-implosion-1.webp",
      "/jewelry/flower-implosion-2.webp",
      "/jewelry/flower-implosion-3.webp",
      "/jewelry/flower-implosion-4.webp",
      "/jewelry/flower-implosion-5.webp",
      "/jewelry/flower-implosion-6.webp",
      "/jewelry/flower-implosion-7.webp",
      "/jewelry/flower-implosion-8.webp",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with white, yellow and dark flower details",
    colorsDe: "Klares Glas mit weißen, gelben und dunklen Blütendetails",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description:
      "Handmade borosilicate pendant with an imploded flower design inside clear glass.",
    descriptionDe:
      "Handgemachter Anhänger aus Borosilikatglas mit einer implodierten Blüte im klaren Glas.",
    story:
      "The flower is built into the glass at the torch, creating depth that changes with the viewing angle.",
    storyDe:
      "Die Blüte wird am Brenner in das Glas eingearbeitet und bekommt dadurch eine Tiefe, die sich je nach Blickwinkel verändert.",
  },  {
    slug: "jellyfish-implosion",
    name: "Jellyfish Implosion",
    nameDe: "Jellyfish Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€50",
    priceDe: "€50",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Jellyfish Implosion (1).JPG",
    images: [
      "/jewelry/Jellyfish Implosion (1).JPG",
      "/jewelry/Jellyfish Implosion (2).JPG",
      "/jewelry/Jellyfish Implosion (3).JPG",
      "/jewelry/Jellyfish Implosion (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Blue and turquoise tones",
    colorsDe: "Blau- und Türkistöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "jetblack-illuminati-arrowhead",
    name: "JetBlack x Illuminati Arrowhead",
    nameDe: "JetBlack x Illuminati Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
    images: [
      "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (2).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (5).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (6).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (16).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "JetBlack and Illuminati",
    colorsDe: "JetBlack und Illuminati",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "licking-chili",
    name: "Licking Chili",
    nameDe: "Licking Chili",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€150",
    priceDe: "€150",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Licking Chili (1).JPG",
    images: [
      "/jewelry/Licking Chili (1).JPG",
      "/jewelry/Licking Chili (2).JPG",
      "/jewelry/Licking Chili (3).JPG",
      "/jewelry/Licking Chili (4).JPG",
      "/jewelry/Licking Chili (5).JPG",
      "/jewelry/Licking Chili (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "metaterrania-moonstone-leaf",
    name: "MetaTerrania x Moonstone Leaf",
    nameDe: "MetaTerrania x Moonstone Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/MetaTerrania x Moonstone Leaf (1).JPG",
    images: [
      "/jewelry/MetaTerrania x Moonstone Leaf (1).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (2).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (3).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "MetaTerrania and Moonstone",
    colorsDe: "MetaTerrania und Moonstone",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "monstera-ns-yellow-ns-irrid",
    name: "Monstera Leaf (NS Yellow x NS Irrid)",
    nameDe: "Monstera Leaf (NS Yellow x NS Irrid)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (NS Yellow x NS Irrid) (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid) (1).JPG",
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid) (2).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "NS Yellow and NS Irrid",
    colorsDe: "NS Yellow und NS Irrid",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "monstera-redmix",
    name: "Monstera Leaf (Redmix)",
    nameDe: "Monstera Leaf (Redmix)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (Redmix) (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (Redmix) (1).JPG",
      "/jewelry/Monstera Leaf (Redmix) (2).JPG",
      "/jewelry/Monstera Leaf (Redmix) (3).JPG",
      "/jewelry/Monstera Leaf (Redmix) (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Redmix",
    colorsDe: "Redmix",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "moonstone-metaterrania-arrowhead",
    name: "Moonstone x MetaTerrania Arrowhead",
    nameDe: "Moonstone x MetaTerrania Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
    images: [
      "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (2).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (3).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Moonstone and MetaTerrania",
    colorsDe: "Moonstone und MetaTerrania",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass arrowhead pendant.",
    descriptionDe: "Handgemachter Arrowhead-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "olea-tree-implosion",
    name: "Olea Tree Implosion",
    nameDe: "Olea Tree Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€65",
    priceDe: "€65",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Olea Tree Implosion (1).JPG",
    images: [
      "/jewelry/Olea Tree Implosion (1).JPG",
      "/jewelry/Olea Tree Implosion (2).JPG",
      "/jewelry/Olea Tree Implosion (3).JPG",
      "/jewelry/Olea Tree Implosion (7).JPG",
      "/jewelry/Olea Tree Implosion (11).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant with a tree implosion.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas mit Baum-Implosion.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "royaljelly-leaf",
    name: "RoyalJelly Leaf",
    nameDe: "RoyalJelly Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Leaf (1).JPG",
    images: [
      "/jewelry/RoyalJelly Leaf (1).JPG",
      "/jewelry/RoyalJelly Leaf (2).JPG",
      "/jewelry/RoyalJelly Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "royaljelly-shroom",
    name: "RoyalJelly Shroom",
    nameDe: "RoyalJelly Shroom",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Shroom (1).JPG",
    images: [
      "/jewelry/RoyalJelly Shroom (1).JPG",
      "/jewelry/RoyalJelly Shroom (2).JPG",
      "/jewelry/RoyalJelly Shroom (3).JPG",
      "/jewelry/RoyalJelly Shroom (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass mushroom pendant.",
    descriptionDe: "Handgemachter Pilz-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "uv-monstera-leaf",
    name: "UV Monstera Leaf",
    nameDe: "UV Monstera Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/UV Monstera Leaf (1).JPG",
    images: [
      "/jewelry/UV Monstera Leaf (1).JPG",
      "/jewelry/UV Monstera Leaf (2).JPG",
      "/jewelry/UV Monstera Leaf (3).JPG",
      "/jewelry/UV Monstera Leaf (4).JPG",
      "/jewelry/UV Monstera Leaf (5).JPG",
      "/jewelry/UV Monstera Leaf (8).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "UV-reactive colors",
    colorsDe: "UV-reaktive Farben",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade UV-reactive borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter UV-reaktiver Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },

  {
    slug: "wooden-leaf",
    name: "Wooden Leaf",
    nameDe: "Wooden Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Wooden Leaf (7).JPG",
    images: [
      "/jewelry/Wooden Leaf (7).JPG",
      "/jewelry/Wooden Leaf (8).JPG",
      "/jewelry/Wooden Leaf (9).JPG",
      "/jewelry/Wooden Leaf (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Earthy tones",
    colorsDe: "Erdige Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2025",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
];
