export const products = [
  {
    slug: "amberpurple-arrowhead",
    name: "AmberPurple Arrowhead",
    nameDe: "AmberPurple Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€80",
    priceDe: "€80",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/AmberPurple Arrowhead (1).JPG",
    images: [
      "/jewelry/AmberPurple Arrowhead (1).JPG",
      "/jewelry/AmberPurple Arrowhead (2).JPG",
      "/jewelry/AmberPurple Arrowhead (3).JPG",
      "/jewelry/AmberPurple Arrowhead (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Amber and purple tones",
    colorsDe: "Amber- und Violetttöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass arrowhead pendant.",
    descriptionDe: "Handgemachter Arrowhead-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "amberpurple-leaf",
    name: "AmberPurple Leaf",
    nameDe: "AmberPurple Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/AmberPurple Leaf (1).JPG",
    images: [
      "/jewelry/AmberPurple Leaf (1).JPG",
      "/jewelry/AmberPurple Leaf (2).JPG",
      "/jewelry/AmberPurple Leaf (3).JPG",
      "/jewelry/AmberPurple Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Amber and purple tones",
    colorsDe: "Amber- und Violetttöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "facetted-suncatcher",
    name: "Facetted Suncatcher",
    nameDe: "Facetted Suncatcher",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€150",
    priceDe: "€150",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Facetted Suncatcher  (1).jpg",
    images: [
      "/jewelry/Facetted Suncatcher  (1).jpg",
      "/jewelry/Facetted Suncatcher  (2).jpg",
      "/jewelry/Facetted Suncatcher  (3).jpg",
      "/jewelry/Facetted Suncatcher  (4).jpg",
      "/jewelry/Facetted Suncatcher  (5).jpg",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with warm reflections",
    colorsDe: "Klares Glas mit warmen Reflexionen",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade faceted borosilicate glass suncatcher.",
    descriptionDe: "Handgemachter facettierter Suncatcher aus Borosilikatglas.",
    story: "The faceted surface changes the reflections depending on the light and viewing angle.",
    storyDe: "Die facettierte Oberfläche verändert die Reflexionen je nach Licht und Blickwinkel.",
  },
  {
    slug: "flower-implosion",
    name: "FlowerImplosion",
    nameDe: "FlowerImplosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€60",
    priceDe: "€60",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/FlowerImplosion (11).JPG",
    images: [
      "/jewelry/FlowerImplosion (11).JPG",
      "/jewelry/FlowerImplosion (5).JPG",
      "/jewelry/FlowerImplosion (8).JPG",
      "/jewelry/FlowerImplosion (9).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with flower details",
    colorsDe: "Klares Glas mit Blütendetails",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant with an imploded flower design.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas mit implodiertem Blütendesign.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "jellyfish-implosion",
    name: "Jellyfish Implosion",
    nameDe: "Jellyfish Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€50",
    priceDe: "€50",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Jellyfish Implosion  (1).JPG",
    images: [
      "/jewelry/Jellyfish Implosion  (1).JPG",
      "/jewelry/Jellyfish Implosion  (2).JPG",
      "/jewelry/Jellyfish Implosion  (3).JPG",
      "/jewelry/Jellyfish Implosion  (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Blue and turquoise tones",
    colorsDe: "Blau- und Türkistöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "jetblack-illuminati-arrowhead",
    name: "JetBlack x Illuminati Arrowhead",
    nameDe: "JetBlack x Illuminati Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
    images: [
      "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (2).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (5).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (6).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (16).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "JetBlack and Illuminati",
    colorsDe: "JetBlack und Illuminati",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "licking-chili",
    name: "Licking Chili",
    nameDe: "Licking Chili",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€150",
    priceDe: "€150",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Licking Chili (1).JPG",
    images: [
      "/jewelry/Licking Chili (1).JPG",
      "/jewelry/Licking Chili (2).JPG",
      "/jewelry/Licking Chili (3).JPG",
      "/jewelry/Licking Chili (4).JPG",
      "/jewelry/Licking Chili (5).JPG",
      "/jewelry/Licking Chili (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "metaterrania-moonstone-leaf",
    name: "MetaTerrania x Moonstone Leaf",
    nameDe: "MetaTerrania x Moonstone Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/MetaTerrania x Moonstone Leaf (3).JPG",
    images: [
      "/jewelry/MetaTerrania x Moonstone Leaf (3).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (1).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (2).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "MetaTerrania and Moonstone",
    colorsDe: "MetaTerrania und Moonstone",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "monstera-ns-yellow-ns-irrid",
    name: "Monstera Leaf (NS Yellow x NS Irrid)",
    nameDe: "Monstera Leaf (NS Yellow x NS Irrid)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (1).JPG",
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (2).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "NS Yellow and NS Irrid",
    colorsDe: "NS Yellow und NS Irrid",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "monstera-redmix",
    name: "Monstera Leaf (Redmix)",
    nameDe: "Monstera Leaf (Redmix)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (Redmix) (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (Redmix) (1).JPG",
      "/jewelry/Monstera Leaf (Redmix) (2).JPG",
      "/jewelry/Monstera Leaf (Redmix) (3).JPG",
      "/jewelry/Monstera Leaf (Redmix) (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Redmix",
    colorsDe: "Redmix",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "moonstone-metaterrania-arrowhead",
    name: "Moonstone x MetaTerrania Arrowhead",
    nameDe: "Moonstone x MetaTerrania Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
    images: [
      "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (2).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (3).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Moonstone and MetaTerrania",
    colorsDe: "Moonstone und MetaTerrania",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass arrowhead pendant.",
    descriptionDe: "Handgemachter Arrowhead-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "olea-tree-implosion",
    name: "Olea Tree Implosion",
    nameDe: "Olea Tree Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€65",
    priceDe: "€65",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Olea Tree Implosion  (1).JPG",
    images: [
      "/jewelry/Olea Tree Implosion  (1).JPG",
      "/jewelry/Olea Tree Implosion  (2).JPG",
      "/jewelry/Olea Tree Implosion  (3).JPG",
      "/jewelry/Olea Tree Implosion  (7).JPG",
      "/jewelry/Olea Tree Implosion  (11).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass pendant with a tree implosion.",
    descriptionDe: "Handgemachter Anhänger aus Borosilikatglas mit Baum-Implosion.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "royaljelly-leaf",
    name: "RoyalJelly Leaf",
    nameDe: "RoyalJelly Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Leaf (1).JPG",
    images: [
      "/jewelry/RoyalJelly Leaf (1).JPG",
      "/jewelry/RoyalJelly Leaf (2).JPG",
      "/jewelry/RoyalJelly Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "royaljelly-shroom",
    name: "RoyalJelly Shroom",
    nameDe: "RoyalJelly Shroom",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Shroom (1).JPG",
    images: [
      "/jewelry/RoyalJelly Shroom (1).JPG",
      "/jewelry/RoyalJelly Shroom (2).JPG",
      "/jewelry/RoyalJelly Shroom (3).JPG",
      "/jewelry/RoyalJelly Shroom (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade borosilicate glass mushroom pendant.",
    descriptionDe: "Handgemachter Pilz-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "uv-monstera-leaf",
    name: "UV Monstera Leaf",
    nameDe: "UV Monstera Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/UV Monstera Leaf  (1).JPG",
    images: [
      "/jewelry/UV Monstera Leaf  (1).JPG",
      "/jewelry/UV Monstera Leaf  (2).JPG",
      "/jewelry/UV Monstera Leaf  (3).JPG",
      "/jewelry/UV Monstera Leaf  (4).JPG",
      "/jewelry/UV Monstera Leaf  (5).JPG",
      "/jewelry/UV Monstera Leaf  (8).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "UV-reactive colors",
    colorsDe: "UV-reaktive Farben",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "Handmade UV-reactive borosilicate Monstera leaf pendant.",
    descriptionDe: "Handgemachter UV-reaktiver Monstera-Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
  {
    slug: "wooden-leaf",
    name: "Wooden Leaf",
    nameDe: "Wooden Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Wooden Leaf (7).JPG",
    images: [
      "/jewelry/Wooden Leaf (7).JPG",
      "/jewelry/Wooden Leaf (8).JPG",
      "/jewelry/Wooden Leaf (9).JPG",
      "/jewelry/Wooden Leaf (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Earthy tones",
    colorsDe: "Erdige Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2025",
    description: "Handmade borosilicate glass leaf pendant.",
    descriptionDe: "Handgemachter Blatt-Anhänger aus Borosilikatglas.",
    story: "Made individually at the torch.",
    storyDe: "Einzeln am Brenner gefertigt.",
  },
];