export const products = [
  {
    slug: "amberpurple-arrowhead",
    name: "AmberPurple Arrowhead",
    nameDe: "AmberPurple Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€80",
    priceDe: "€80",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/AmberPurple Arrowhead (1).JPG",
    images: [
      "/jewelry/AmberPurple Arrowhead (1).JPG",
      "/jewelry/AmberPurple Arrowhead (2).JPG",
      "/jewelry/AmberPurple Arrowhead (3).JPG",
      "/jewelry/AmberPurple Arrowhead (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Amber and purple tones",
    colorsDe: "Amber- und Violetttöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A handmade borosilicate arrowhead pendant where warm amber tones flow into deep purple. The pointed silhouette gives the piece a strong, almost talisman-like presence while the glass keeps it light and fluid.",
    descriptionDe: "Ein handgemachter Arrowhead-Anhänger aus Borosilikatglas, bei dem warme Ambertöne in tiefes Violett übergehen. Die klare, spitze Form wirkt fast wie ein kleiner Talisman, während das Glas trotzdem leicht und fließend bleibt.",
    story: "“Between ember and dusk.” A compact piece built around contrast: warm color, cool depth and a sharp outline shaped entirely at the torch.",
    storyDe: "„Zwischen Glut und Dämmerung.“ Ein kompaktes Stück aus Kontrasten: warme Farbe, kühle Tiefe und eine markante Form, komplett an der Flamme entstanden.",
  },
  {
    slug: "amberpurple-leaf",
    name: "AmberPurple Leaf",
    nameDe: "AmberPurple Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/AmberPurple Leaf (1).JPG",
    images: [
      "/jewelry/AmberPurple Leaf (1).JPG",
      "/jewelry/AmberPurple Leaf (2).JPG",
      "/jewelry/AmberPurple Leaf (3).JPG",
      "/jewelry/AmberPurple Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Amber and purple tones",
    colorsDe: "Amber- und Violetttöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "An organic leaf pendant made from borosilicate glass, combining warm amber with purple tones that shift with the light. The natural outline and flowing color make every angle feel slightly different.",
    descriptionDe: "Ein organisch geformter Blatt-Anhänger aus Borosilikatglas, der warme Amber- mit Violetttönen verbindet. Je nach Licht und Blickwinkel verändert sich die Wirkung der Farben und macht jede Ansicht ein wenig anders.",
    story: "“Autumn, but molten.” A leaf form translated into glass without trying to copy nature perfectly — more like a memory of it shaped in the flame.",
    storyDe: "„Herbst, nur geschmolzen.“ Eine Blattform in Glas übersetzt, ohne die Natur exakt kopieren zu wollen – eher wie eine Erinnerung daran, in der Flamme geformt.",
  },
  {
    slug: "facetted-suncatcher",
    name: "Facetted Suncatcher",
    nameDe: "Facetted Suncatcher",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€150",
    priceDe: "€150",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Facetted Suncatcher  (1).jpg",
    images: [
      "/jewelry/Facetted Suncatcher  (1).jpg",
      "/jewelry/Facetted Suncatcher  (2).jpg",
      "/jewelry/Facetted Suncatcher  (3).jpg",
      "/jewelry/Facetted Suncatcher  (4).jpg",
      "/jewelry/Facetted Suncatcher  (5).jpg",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with warm reflections",
    colorsDe: "Klares Glas mit warmen Reflexionen",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A faceted borosilicate glass suncatcher made to interact with daylight. Its clear surfaces catch, split and redirect reflections, so the piece keeps changing as the light and viewing angle move.",
    descriptionDe: "Ein facettierter Suncatcher aus Borosilikatglas, der mit Tageslicht spielt. Die klaren Flächen fangen Reflexionen ein und lenken sie weiter, wodurch sich das Stück mit Licht und Blickwinkel ständig verändert.",
    story: "“Light never hits it the same way twice.” Here the glass itself stays quiet and lets reflections, edges and movement do the work.",
    storyDe: "„Licht trifft es nie zweimal gleich.“ Hier bleibt das Glas selbst zurückhaltend und überlässt Reflexionen, Kanten und Bewegung die Hauptrolle.",
  },
  {
    slug: "flower-implosion",
    name: "FlowerImplosion",
    nameDe: "FlowerImplosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€60",
    priceDe: "€60",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/FlowerImplosion (11).JPG",
    images: [
      "/jewelry/FlowerImplosion (11).JPG",
      "/jewelry/FlowerImplosion (5).JPG",
      "/jewelry/FlowerImplosion (8).JPG",
      "/jewelry/FlowerImplosion (9).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Clear glass with flower details",
    colorsDe: "Klares Glas mit Blütendetails",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A flower suspended inside clear borosilicate glass, created with the implosion technique. The flower is not cast or inserted: the color pattern is built at the torch and controlled heat together with gravity pulls it inward into the glass.",
    descriptionDe: "Eine Blüte, die im klaren Borosilikatglas zu schweben scheint und mit der Implosionstechnik entsteht. Die Blüte wird weder gegossen noch eingesetzt: Das Farbmuster wird an der Flamme aufgebaut und durch kontrollierte Hitze zusammen mit der Schwerkraft ins Glas hineingezogen.",
    story: "“Gravity draws the bloom inward.” What starts as a flat pattern at the surface develops depth step by step until it becomes a small three-dimensional flower inside the glass.",
    storyDe: "„Die Schwerkraft zieht die Blüte nach innen.“ Was als flaches Muster an der Oberfläche beginnt, bekommt Schritt für Schritt Tiefe, bis daraus eine kleine dreidimensionale Blüte im Glas entsteht.",
  },
  {
    slug: "jellyfish-implosion",
    name: "Jellyfish Implosion",
    nameDe: "Jellyfish Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€50",
    priceDe: "€50",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Jellyfish Implosion  (1).JPG",
    images: [
      "/jewelry/Jellyfish Implosion  (1).JPG",
      "/jewelry/Jellyfish Implosion  (2).JPG",
      "/jewelry/Jellyfish Implosion  (3).JPG",
      "/jewelry/Jellyfish Implosion  (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Blue and turquoise tones",
    colorsDe: "Blau- und Türkistöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A blue and turquoise implosion pendant with soft lines that seem to drift through the clear glass. The depth of the pattern gives it the feeling of a tiny jellyfish floating below the surface.",
    descriptionDe: "Ein Implosions-Anhänger in Blau- und Türkistönen, dessen weiche Linien durch das klare Glas zu treiben scheinen. Die Tiefe des Musters erinnert an eine kleine Qualle, die unter der Oberfläche schwebt.",
    story: "“A small drift through deep water.” The form appeared somewhere between planned pattern and the natural movement of hot glass — exactly the kind of accident worth keeping.",
    storyDe: "„Ein kleines Treiben im tiefen Wasser.“ Die Form entstand irgendwo zwischen geplantem Muster und der natürlichen Bewegung von heißem Glas – genau die Art von Zufall, die man behalten will.",
  },
  {
    slug: "jetblack-illuminati-arrowhead",
    name: "JetBlack x Illuminati Arrowhead",
    nameDe: "JetBlack x Illuminati Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
    images: [
      "/jewelry/JetBlack x Illuminati Arrowhead (1).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (2).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (5).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (6).JPG",
      "/jewelry/JetBlack x Illuminati Arrowhead (16).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "JetBlack and Illuminati",
    colorsDe: "JetBlack und Illuminati",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A bold borosilicate arrowhead pendant built around the contrast between JetBlack and Illuminati. Dark areas frame the brighter color and give the pointed form extra depth and definition.",
    descriptionDe: "Ein markanter Arrowhead-Anhänger aus Borosilikatglas, aufgebaut auf dem Kontrast von JetBlack und Illuminati. Die dunklen Bereiche rahmen die hellere Farbe ein und geben der spitzen Form zusätzliche Tiefe und Kontur.",
    story: "“Dark outside, electric within.” A sharper and more graphic piece than most of my organic work, with the color contrast doing most of the talking.",
    storyDe: "„Außen dunkel, innen elektrisch.“ Ein kantigeres und grafischeres Stück als viele meiner organischen Arbeiten, bei dem vor allem der Farbkontrast spricht.",
  },
  {
    slug: "licking-chili",
    name: "Licking Chili",
    nameDe: "Licking Chili",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€150",
    priceDe: "€150",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Licking Chili (1).JPG",
    images: [
      "/jewelry/Licking Chili (1).JPG",
      "/jewelry/Licking Chili (2).JPG",
      "/jewelry/Licking Chili (3).JPG",
      "/jewelry/Licking Chili (4).JPG",
      "/jewelry/Licking Chili (5).JPG",
      "/jewelry/Licking Chili (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A playful sculptural borosilicate pendant with the attitude of a chili that refuses to behave. More character than classic jewelry, this piece sits somewhere between wearable glass, tiny sculpture and a visual joke.",
    descriptionDe: "Ein verspielter, skulpturaler Anhänger aus Borosilikatglas mit dem Charakter einer Chili, die sich nicht benehmen will. Weniger klassischer Schmuck, mehr tragbares Glasobjekt irgendwo zwischen Mini-Skulptur und visuellem Witz.",
    story: "“Too hot to behave.” This is one of those pieces that started with a simple form and ended up developing its own personality at the torch.",
    storyDe: "„Zu heiß, um sich zu benehmen.“ Eines dieser Stücke, die mit einer einfachen Form beginnen und an der Flamme plötzlich ihre ganz eigene Persönlichkeit entwickeln.",
  },
  {
    slug: "metaterrania-moonstone-leaf",
    name: "MetaTerrania x Moonstone Leaf",
    nameDe: "MetaTerrania x Moonstone Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/MetaTerrania x Moonstone Leaf (3).JPG",
    images: [
      "/jewelry/MetaTerrania x Moonstone Leaf (3).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (1).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (2).JPG",
      "/jewelry/MetaTerrania x Moonstone Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "MetaTerrania and Moonstone",
    colorsDe: "MetaTerrania und Moonstone",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "An organic borosilicate leaf combining MetaTerrania with Moonstone. Earthy, mineral-like tones meet a softer pale color, giving the leaf a calm depth that changes noticeably between direct and softer light.",
    descriptionDe: "Ein organischer Blatt-Anhänger aus Borosilikatglas, der MetaTerrania mit Moonstone verbindet. Erdige, mineralische Töne treffen auf eine weichere helle Farbe und geben dem Blatt eine ruhige Tiefe, die sich je nach Licht deutlich verändert.",
    story: "“Earth meets moonlight.” This color combination feels like two opposite materials meeting in one piece — grounded and soft at the same time.",
    storyDe: "„Erde trifft Mondlicht.“ Die Farbkombination wirkt für mich wie zwei Gegensätze in einem Stück – geerdet und gleichzeitig weich.",
  },
  {
    slug: "monstera-ns-yellow-ns-irrid",
    name: "Monstera Leaf (NS Yellow x NS Irrid)",
    nameDe: "Monstera Leaf (NS Yellow x NS Irrid)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (1).JPG",
      "/jewelry/Monstera Leaf (NS Yellow x NS Irrid)  (2).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "NS Yellow and NS Irrid",
    colorsDe: "NS Yellow und NS Irrid",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A handmade Monstera leaf pendant in NS Yellow and NS Irrid. The tropical silhouette is kept clean and recognizable while the color combination adds a warmer, more unusual character than a natural green leaf.",
    descriptionDe: "Ein handgemachter Monstera-Blatt-Anhänger in NS Yellow und NS Irrid. Die tropische Silhouette bleibt klar erkennbar, während die Farbkombination dem Blatt einen wärmeren und ungewöhnlicheren Charakter als klassisches Grün gibt.",
    story: "“Tropical, with a little fire in it.” I like taking familiar natural forms and pushing them somewhere less expected through color.",
    storyDe: "„Tropisch, mit ein bisschen Feuer darin.“ Ich mag es, vertraute Formen aus der Natur zu nehmen und sie über die Farbe in eine unerwartetere Richtung zu schieben.",
  },
  {
    slug: "monstera-redmix",
    name: "Monstera Leaf (Redmix)",
    nameDe: "Monstera Leaf (Redmix)",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Monstera Leaf (Redmix) (1).JPG",
    images: [
      "/jewelry/Monstera Leaf (Redmix) (1).JPG",
      "/jewelry/Monstera Leaf (Redmix) (2).JPG",
      "/jewelry/Monstera Leaf (Redmix) (3).JPG",
      "/jewelry/Monstera Leaf (Redmix) (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Redmix",
    colorsDe: "Redmix",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A Monstera leaf pendant built around a layered red color mix. The familiar plant shape becomes more intense and graphic in glass, with different red tones revealing themselves depending on thickness and light.",
    descriptionDe: "Ein Monstera-Blatt-Anhänger mit einem geschichteten Redmix. Die vertraute Pflanzenform wirkt im Glas kräftiger und grafischer, wobei je nach Glasstärke und Licht unterschiedliche Rottöne sichtbar werden.",
    story: "“A leaf turned up to red.” Natural shape, unnatural color — a simple contrast that gives this piece most of its energy.",
    storyDe: "„Eine Blattform voll auf Rot gedreht.“ Natürliche Form, unnatürliche Farbe – ein einfacher Kontrast, der dem Stück den Großteil seiner Energie gibt.",
  },
  {
    slug: "moonstone-metaterrania-arrowhead",
    name: "Moonstone x MetaTerrania Arrowhead",
    nameDe: "Moonstone x MetaTerrania Arrowhead",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
    images: [
      "/jewelry/Moonstone x MetaTerrania Arrowhead (1).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (2).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (3).JPG",
      "/jewelry/Moonstone x MetaTerrania Arrowhead (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Moonstone and MetaTerrania",
    colorsDe: "Moonstone und MetaTerrania",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A borosilicate arrowhead pendant combining the pale softness of Moonstone with the earthy depth of MetaTerrania. The pointed shape gives the calm color palette a stronger, more defined character.",
    descriptionDe: "Ein Arrowhead-Anhänger aus Borosilikatglas, der die helle, weiche Wirkung von Moonstone mit der erdigen Tiefe von MetaTerrania verbindet. Die spitze Form gibt der ruhigen Farbpalette einen stärkeren, klareren Charakter.",
    story: "“Moonlight with an earthy core.” Soft color does not have to mean a soft shape — this piece is built around exactly that tension.",
    storyDe: "„Mondlicht mit einem erdigen Kern.“ Eine weiche Farbe muss keine weiche Form bedeuten – genau auf diesem Gegensatz baut das Stück auf.",
  },
  {
    slug: "olea-tree-implosion",
    name: "Olea Tree Implosion",
    nameDe: "Olea Tree Implosion",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€65",
    priceDe: "€65",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Olea Tree Implosion  (1).JPG",
    images: [
      "/jewelry/Olea Tree Implosion  (1).JPG",
      "/jewelry/Olea Tree Implosion  (2).JPG",
      "/jewelry/Olea Tree Implosion  (3).JPG",
      "/jewelry/Olea Tree Implosion  (7).JPG",
      "/jewelry/Olea Tree Implosion  (11).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Mixed colors",
    colorsDe: "Verschiedene Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A tree-like implosion captured inside clear borosilicate glass. Fine branching structures create the impression of a tiny Olea tree with depth that only becomes fully visible as the pendant is turned in the hand.",
    descriptionDe: "Eine baumartige Implosion, eingefangen in klarem Borosilikatglas. Feine Verzweigungen erinnern an einen kleinen Olea-Baum und zeigen ihre räumliche Tiefe erst richtig, wenn man den Anhänger in der Hand dreht.",
    story: "“A tree caught in glass.” I am interested in the point where a controlled pattern stops looking technical and suddenly starts feeling alive.",
    storyDe: "„Ein Baum, eingefangen im Glas.“ Mich interessiert der Moment, in dem ein kontrolliertes Muster nicht mehr technisch aussieht und plötzlich etwas Lebendiges bekommt.",
  },
  {
    slug: "royaljelly-leaf",
    name: "RoyalJelly Leaf",
    nameDe: "RoyalJelly Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€120",
    priceDe: "€120",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Leaf (1).JPG",
    images: [
      "/jewelry/RoyalJelly Leaf (1).JPG",
      "/jewelry/RoyalJelly Leaf (2).JPG",
      "/jewelry/RoyalJelly Leaf (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A clean organic leaf pendant made in Royal Jelly borosilicate glass. The soft, creamy color gives the familiar leaf form a slightly surreal character while keeping the overall piece calm and wearable.",
    descriptionDe: "Ein klar geformter, organischer Blatt-Anhänger aus Royal-Jelly-Borosilikatglas. Die weiche, cremige Farbe gibt der vertrauten Blattform einen leicht surrealen Charakter, ohne dass das Stück seine ruhige Wirkung verliert.",
    story: "“Soft color, sharp silhouette.” Sometimes one color and one strong outline are enough — the glass and the light can do the rest.",
    storyDe: "„Weiche Farbe, klare Silhouette.“ Manchmal reichen eine Farbe und eine starke Form – den Rest können Glas und Licht übernehmen.",
  },
  {
    slug: "royaljelly-shroom",
    name: "RoyalJelly Shroom",
    nameDe: "RoyalJelly Shroom",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/RoyalJelly Shroom (1).JPG",
    images: [
      "/jewelry/RoyalJelly Shroom (1).JPG",
      "/jewelry/RoyalJelly Shroom (2).JPG",
      "/jewelry/RoyalJelly Shroom (3).JPG",
      "/jewelry/RoyalJelly Shroom (4).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Royal Jelly",
    colorsDe: "Royal Jelly",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A small sculptural mushroom pendant made from Royal Jelly borosilicate glass. Its soft color and rounded organic form make it playful without turning it into a perfectly polished or symmetrical little object.",
    descriptionDe: "Ein kleiner skulpturaler Pilz-Anhänger aus Royal-Jelly-Borosilikatglas. Die weiche Farbe und die runde organische Form wirken verspielt, ohne dass daraus ein perfekt poliertes oder symmetrisches kleines Objekt werden soll.",
    story: "“A strange little thing from the forest floor.” I like objects that feel familiar at first glance and slightly odd a second later.",
    storyDe: "„Ein seltsames kleines Ding vom Waldboden.“ Ich mag Objekte, die im ersten Moment vertraut wirken und eine Sekunde später ein bisschen eigenartig.",
  },
  {
    slug: "uv-monstera-leaf",
    name: "UV Monstera Leaf",
    nameDe: "UV Monstera Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€85",
    priceDe: "€85",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/UV Monstera Leaf  (1).JPG",
    images: [
      "/jewelry/UV Monstera Leaf  (1).JPG",
      "/jewelry/UV Monstera Leaf  (2).JPG",
      "/jewelry/UV Monstera Leaf  (3).JPG",
      "/jewelry/UV Monstera Leaf  (4).JPG",
      "/jewelry/UV Monstera Leaf  (5).JPG",
      "/jewelry/UV Monstera Leaf  (8).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "UV-reactive colors",
    colorsDe: "UV-reaktive Farben",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2026",
    description: "A handmade Monstera leaf pendant using UV-reactive borosilicate colors. In normal light it reads as an organic glass leaf; under UV light another side of the color becomes visible and changes the whole mood of the piece.",
    descriptionDe: "Ein handgemachter Monstera-Blatt-Anhänger mit UV-reaktiven Borosilikatfarben. Bei normalem Licht wirkt er wie ein organisches Glasblatt, unter UV-Licht zeigt die Farbe eine zweite Seite und verändert die gesamte Stimmung des Stücks.",
    story: "“One piece, two moods.” I enjoy glass that keeps something hidden until the light changes — a small transformation built directly into the material.",
    storyDe: "„Ein Stück, zwei Stimmungen.“ Ich mag Glas, das etwas versteckt hält, bis sich das Licht verändert – eine kleine Verwandlung, die direkt im Material steckt.",
  },
  {
    slug: "wooden-leaf",
    name: "Wooden Leaf",
    nameDe: "Wooden Leaf",
    category: "Jewelry",
    categoryDe: "Schmuck",
    price: "€100",
    priceDe: "€100",
    status: "Available",
    statusDe: "Verfügbar",
    image: "/jewelry/Wooden Leaf (7).JPG",
    images: [
      "/jewelry/Wooden Leaf (7).JPG",
      "/jewelry/Wooden Leaf (8).JPG",
      "/jewelry/Wooden Leaf (9).JPG",
      "/jewelry/Wooden Leaf (10).JPG",
    ],
    material: "Borosilicate glass",
    materialDe: "Borosilikatglas",
    colors: "Earthy tones",
    colorsDe: "Erdige Farbtöne",
    size: "Size details coming soon",
    sizeDe: "Größenangaben folgen",
    year: "2025",
    description: "A borosilicate leaf pendant in layered earthy tones that give the glass an almost wood-like appearance. It plays with the contradiction between a material that looks warm and natural while actually being hard, clear and formed in fire.",
    descriptionDe: "Ein Blatt-Anhänger aus Borosilikatglas in geschichteten Erdtönen, die dem Glas eine fast holzartige Wirkung geben. Das Stück spielt mit dem Gegensatz zwischen einer warmen, natürlichen Optik und einem Material, das hart, glasig und im Feuer geformt ist.",
    story: "“Glass pretending to be wood.” One material borrowing the visual language of another — a small experiment in texture, color and expectation.",
    storyDe: "„Glas, das so tut, als wäre es Holz.“ Ein Material leiht sich die Optik eines anderen – ein kleines Experiment mit Struktur, Farbe und Erwartung.",
  },
];