export type SiteContentMap = Record<string, string>;

export const SITE_CONTENT_DEFAULTS: SiteContentMap = {
  "home.hero.subtitle.en": "Borosilicate glass · Carinthia, Austria",
  "home.hero.subtitle.de": "Borosilikatglas · Kärnten, Österreich",
  "home.hero.text.en": "I’m Florian Robatsch, a glass artist from Carinthia. At the torch I turn borosilicate glass into one-of-a-kind jewelry, objects and whatever ideas happen to stick in my head.",
  "home.hero.text.de": "Ich bin Florian Robatsch, Glaskünstler aus Kärnten. Am Brenner entstehen aus Borosilikatglas handgemachte Unikate – Schmuck, Objekte und alles, was mir sonst noch durch den Kopf geht.",
  "home.hero.cta.en": "See the work",
  "home.hero.cta.de": "Arbeiten ansehen",
  "home.hero.media.url": "/workshop/me2.jpg",
  "home.hero.media.type": "image",

  "home.jewelry.eyebrow.en": "Jewelry",
  "home.jewelry.eyebrow.de": "Schmuck",
  "home.jewelry.title.en": "Glass to wear",
  "home.jewelry.title.de": "Glas zum Tragen",
  "home.jewelry.intro.en": "Handmade borosilicate glass pendants from Austria. Every piece is made individually at the torch and is one of a kind.",
  "home.jewelry.intro.de": "Handgemachte Anhänger aus Borosilikatglas aus Österreich. Jedes Stück entsteht einzeln am Brenner und ist ein Unikat.",

  "home.workshop.eyebrow.en": "Workshop",
  "home.workshop.eyebrow.de": "Werkstatt",
  "home.workshop.title.en": "Glass in the flame",
  "home.workshop.title.de": "Glas in der Flamme",
  "home.workshop.text.en": "This is where the pieces begin. Borosilicate glass is heated at the torch, kept in motion and shaped step by step. Some pieces start from a clear idea, while others only reveal their direction during the process.",
  "home.workshop.text.de": "Hier beginnt jedes Stück. Borosilikatglas wird am Brenner erhitzt, ständig in Bewegung gehalten und Schritt für Schritt geformt. Manche Arbeiten starten mit einer klaren Idee, andere zeigen erst während des Prozesses, wohin sie sich entwickeln.",
  "home.workshop.main.url": "/workshop/me2.jpg",
  "home.workshop.main.type": "image",
  "home.workshop.media1.url": "/jewelry/Cobald5 x Opaldust Leaf.jpg",
  "home.workshop.media1.type": "image",
  "home.workshop.media2.url": "/workshop/me2.jpg",
  "home.workshop.media2.type": "image",

  "home.reviews.eyebrow.en": "Community",
  "home.reviews.eyebrow.de": "Community",
  "home.reviews.title.en": "What others say",
  "home.reviews.title.de": "Was andere sagen",
  "home.reviews.button.en": "View all",
  "home.reviews.button.de": "Alle ansehen",

  "home.studio.eyebrow.en": "Studio",
  "home.studio.eyebrow.de": "Werkstatt",
  "home.studio.title.en": "Fire, glass and craft",
  "home.studio.title.de": "Feuer, Glas und Handwerk",
  "home.studio.text.en": "A closer look at the place where I work with borosilicate glass, test ideas and gradually develop the studio further.",
  "home.studio.text.de": "Ein genauerer Blick auf den Ort, an dem ich mit Borosilikatglas arbeite, Ideen ausprobiere und die Werkstatt Schritt für Schritt weiterentwickle.",
  "home.studio.button.en": "Explore the studio",
  "home.studio.button.de": "Zur Werkstatt",
  "home.studio.media.url": "/workshop/me2.jpg",
  "home.studio.media.type": "image",

  "studio.eyebrow.en": "Workspace",
  "studio.eyebrow.de": "Werkstatt",
  "studio.title.en": "Fire, glass and craft",
  "studio.title.de": "Feuer, Glas und Handwerk",
  "studio.intro.en": "My workshop in Carinthia is where ideas become glass. I work with borosilicate glass directly at the torch, combining heat, movement and patience until a form begins to emerge. The space is still evolving — just like the work that is made here.",
  "studio.intro.de": "Meine Werkstatt in Kärnten ist der Ort, an dem aus Ideen Glas wird. Ich arbeite direkt am Brenner mit Borosilikatglas und verbinde Hitze, Bewegung und Geduld, bis sich eine Form entwickelt. Der Raum wächst dabei genauso weiter wie die Arbeiten, die hier entstehen.",
  "studio.card1.title.en": "Torch space",
  "studio.card1.title.de": "Brennerplatz",
  "studio.card1.text.en": "Later I would like to make a properly equipped torch space available by arrangement to glassworkers who already have experience and want to work independently.",
  "studio.card1.text.de": "Später möchte ich einen gut ausgestatteten Brennerplatz nach Absprache auch Glasarbeitern mit eigener Erfahrung zur Verfügung stellen, die selbstständig arbeiten möchten.",
  "studio.card2.title.en": "Small workshops",
  "studio.card2.title.de": "Kleine Workshops",
  "studio.card2.text.en": "For beginners I am planning small, personal sessions that focus on the material, safe handling at the torch and the first steps toward a piece of their own.",
  "studio.card2.text.de": "Für Einsteiger sind kleine, persönliche Sessions geplant, bei denen das Material, der sichere Umgang am Brenner und die ersten Schritte zum eigenen Stück im Mittelpunkt stehen.",
  "studio.card3.title.en": "Exchange",
  "studio.card3.title.de": "Austausch",
  "studio.card3.text.en": "The studio should also be a place for meeting other glassworkers, sharing techniques and ideas, and sometimes simply working next to each other.",
  "studio.card3.text.de": "Die Werkstatt soll auch Raum für Austausch mit anderen Glasarbeitern bieten – für Techniken, Ideen und manchmal einfach für gemeinsames Arbeiten am Brenner.",
  "studio.card4.title.en": "Individual sessions",
  "studio.card4.title.de": "Individuelle Sessions",
  "studio.card4.text.en": "Depending on time, setup and experience, individual sessions or focused projects may also become possible later on.",
  "studio.card4.text.de": "Je nach Zeit, Ausstattung und Erfahrung sollen später auch individuelle Sessions oder gezielte Projekte möglich werden.",
  "studio.vision.en": "The studio is not meant to become a fixed concept overnight. I am building it up step by step, learning what works and leaving enough space for it to grow naturally.",
  "studio.vision.de": "Die Werkstatt soll nicht von heute auf morgen zu einem fertigen Konzept werden. Ich baue sie Schritt für Schritt weiter aus, sehe was funktioniert und lasse genug Raum, damit sie sich natürlich entwickeln kann.",
  "studio.contact.eyebrow.en": "Workshop",
  "studio.contact.eyebrow.de": "Werkstatt",
  "studio.contact.title.en": "Curious about glass?",
  "studio.contact.title.de": "Neugierig auf Glas?",
  "studio.contact.text.en": "If torch time, a future workshop or simply an exchange about borosilicate glass interests you, send me a message. We can work out the details personally.",
  "studio.contact.text.de": "Wenn dich Werkstattzeit, ein späterer Workshop oder einfach der Austausch über Borosilikatglas interessiert, schreib mir. Alles Weitere können wir persönlich besprechen.",
  "studio.contact.button.en": "Send a message",
  "studio.contact.button.de": "Nachricht senden",

  "about.eyebrow.en": "Biography",
  "about.eyebrow.de": "Biografie",
  "about.p1.en": "Hey, my name is Florian Robatsch and I'm from Carinthia, Austria. Since 2019, I have been working with borosilicate glass and discovered my passion for lampworking – a special form of glasswork at the flame.",
  "about.p1.de": "Hey, mein Name ist Florian Robatsch und ich komme aus Kärnten, Österreich. Seit 2019 beschäftige ich mich mit Borosilikatglas und habe dabei meine Leidenschaft für das Lampworking entdeckt – eine besondere Form der Glasbearbeitung an der Flamme.",
  "about.p2.en": "What continues to fascinate me about it is the combination of precision and creativity. With a steady hand and a lot of heat, a hard and robust material can become something light, playful and often completely unexpected.",
  "about.p2.de": "Was mich daran bis heute fasziniert, ist die Verbindung aus Präzision und Kreativität. Mit ruhiger Hand und viel Hitze entsteht aus einem eigentlich harten und robusten Material etwas Leichtes, Verspieltes und oft ganz Unerwartetes.",
  "about.p3.en": "My work usually develops from a mixture of intuition, ideas and the joy of experimenting. I try not to plan every detail in advance, but instead leave some space for the glass and the process itself. I especially enjoy working with organic shapes, colors and details that give my pieces a natural and sometimes dreamlike character.",
  "about.p3.de": "Meine Arbeiten entstehen meist aus einer Mischung aus Intuition, Ideen und der Freude am Experimentieren. Ich versuche dabei nicht, jedes Detail im Voraus festzulegen, sondern lasse dem Glas und dem Entstehungsprozess auch etwas Raum. Besonders gerne arbeite ich mit organischen Formen, Farben und Details, die meinen Stücken einen natürlichen und manchmal verträumten Charakter geben.",
  "about.p4.en": "Not every piece develops exactly the way I originally imagined – and that is part of the process for me. I still find it fascinating to create something individual from glass that feels delicate and alive at the same time.",
  "about.p4.de": "Nicht jedes Stück entwickelt sich genau so, wie ich es ursprünglich geplant habe – und gerade das gehört für mich dazu. Es begeistert mich immer wieder, aus Glas etwas Eigenständiges zu erschaffen, das filigran und gleichzeitig lebendig wirkt.",
  "about.media.url": "/workshop/me2.jpg",
  "about.media.type": "image",

  "shop.eyebrow.en": "Shop",
  "shop.eyebrow.de": "Shop",
  "shop.title.en": "Available pieces",
  "shop.title.de": "Verfügbare Stücke",
  "shop.intro.en": "These pieces are currently available. Open a piece to see all details and send an inquiry from there.",
  "shop.intro.de": "Diese Stücke sind aktuell verfügbar. Öffne ein Stück für alle Details und stelle deine Anfrage direkt auf der Produktseite.",

  "gallery.eyebrow.en": "Gallery",
  "gallery.eyebrow.de": "Galerie",
  "gallery.intro.en": "A selection of jewelry, objects and experiments made in the workshop.",
  "gallery.intro.de": "Eine Auswahl an Schmuck, Objekten und Experimenten aus der Werkstatt.",
  "gallery.media1.url": "/jewelry/Cobald5 x Opaldust Leaf.jpg",
  "gallery.media1.type": "image",
  "gallery.media2.url": "/jewelry/leaf2.jpg",
  "gallery.media2.type": "image",
  "gallery.media3.url": "/jewelry/AmberPurple Leaf STube (2).JPG",
  "gallery.media3.type": "image",
  "gallery.media4.url": "/jewelry/leaf4.jpg",
  "gallery.media4.type": "image",
  "gallery.media5.url": "/jewelry/leaf5.jpg",
  "gallery.media5.type": "image",
  "gallery.media6.url": "/jewelry/implo.jpg",
  "gallery.media6.type": "image",
  "gallery.media7.url": "/jewelry/Barkylett.JPG",
  "gallery.media7.type": "image",
  "gallery.media8.url": "/jewelry/Customer.JPG",
  "gallery.media8.type": "image",
  "gallery.media9.url": "/jewelry/IMG_2173 4.JPG",
  "gallery.media9.type": "image",
  "gallery.media10.url": "/jewelry/Mini Heart.JPG",
  "gallery.media10.type": "image",
};

export function siteContentValue(
  content: SiteContentMap,
  key: string,
  fallback = "",
) {
  return Object.prototype.hasOwnProperty.call(content, key)
    ? content[key]
    : fallback;
}
