export type SiteContentMap = Record<string, string>;

export const SITE_CONTENT_DEFAULTS: SiteContentMap = {
  "home.hero.subtitle.en": "Borosilicate glass · Carinthia, Austria",
  "home.hero.subtitle.de": "Borosilikatglas · Kärnten, Österreich",
  "home.hero.text.en": "I’m Florian Robatsch, a glass artist from Carinthia. At the torch I turn borosilicate glass into one-of-a-kind jewelry, objects and whatever ideas happen to stick in my head.",
  "home.hero.text.de": "Ich bin Florian Robatsch, Glaskünstler aus Kärnten. Am Brenner entstehen aus Borosilikatglas handgemachte Unikate – Schmuck, Objekte und alles, was mir sonst noch durch den Kopf geht.",
  "home.hero.tag1.en": "Lampworking",
  "home.hero.tag1.de": "Lampworking",
  "home.hero.tag2.en": "Jewelry",
  "home.hero.tag2.de": "Schmuck",
  "home.hero.tag3.en": "Objects",
  "home.hero.tag3.de": "Objekte",
  "home.hero.cta.en": "See the work",
  "home.hero.cta.de": "Arbeiten ansehen",
  "home.hero.media.url": "/workshop/me2.jpg",
  "home.hero.media.type": "image",

  "home.jewelry.eyebrow.en": "Jewelry",
  "home.jewelry.eyebrow.de": "Schmuck",
  "home.jewelry.title.en": "Glass to wear",
  "home.jewelry.title.de": "Glas zum Tragen",
  "home.jewelry.intro.en": "Handmade borosilicate glass pendants from Austria. Every piece is made individually at the torch and is one of a kind.",
  "home.jewelry.intro.de": "Handgemachte Anhänger aus Borosilikatglas aus Österreich. Jedes Stück entsteht einzeln am Brenner und ist ein Unikat.",

  "home.workshop.eyebrow.en": "Workshop",
  "home.workshop.eyebrow.de": "Werkstatt",
  "home.workshop.title.en": "At the torch",
  "home.workshop.title.de": "Am Brenner",
  "home.workshop.text.en": "I make each piece by hand from borosilicate glass in my workshop in Carinthia. Some pieces start with a clear idea, while others only reveal their direction while I work.",
  "home.workshop.text.de": "In meiner Werkstatt in Kärnten fertige ich jedes Stück von Hand aus Borosilikatglas am Brenner. Manche Arbeiten starten mit einer klaren Idee, andere zeigen erst während der Arbeit, wohin sie sich entwickeln.",
  "home.workshop.text2.en": "What interests me is not only the finished piece, but also the process: how color, depth and form emerge directly in the flame and keep changing while I work.",
  "home.workshop.text2.de": "Mich interessiert dabei nicht nur das fertige Stück, sondern auch der Weg dorthin: wie Farbe, Tiefe und Form direkt in der Flamme entstehen und sich während der Arbeit verändern.",
  "home.workshop.button.en": "More from the studio",
  "home.workshop.button.de": "Mehr aus der Werkstatt",
  "home.workshop.main.url": "/workshop/me2.jpg",
  "home.workshop.main.type": "image",
  "home.workshop.media1.url": "/jewelry/Cobald5 x Opaldust Leaf.jpg",
  "home.workshop.media1.type": "image",
  "home.workshop.media2.url": "/workshop/me2.jpg",
  "home.workshop.media2.type": "image",

  "home.reviews.eyebrow.en": "Community",
  "home.reviews.eyebrow.de": "Community",
  "home.reviews.title.en": "What others say",
  "home.reviews.title.de": "Was andere sagen",
  "home.reviews.button.en": "View all",
  "home.reviews.button.de": "Alle ansehen",

  "home.studio.title.en": "The workspace",
  "home.studio.title.de": "Der Arbeitsplatz",
  "home.studio.text.en": "A quick look at my workspace, the setup and my plans for future torch time, workshops and a possible studio spot.",
  "home.studio.text.de": "Ein kleiner Einblick in meinen Arbeitsplatz, die Ausstattung und meine Pläne für Brennerzeit, Workshops und einen möglichen Studioplatz.",

  "studio.eyebrow.en": "Workspace",
  "studio.eyebrow.de": "Werkstatt",
  "studio.title.en": "Fire, glass and craft",
  "studio.title.de": "Feuer, Glas und Handwerk",
  "studio.intro.en": "My workshop in Carinthia is where glass rods and tubes become jewelry, small objects, experiments and one-off pieces. I work with borosilicate glass (COE 33), heating it to working temperature in an oxygen/gas flame and shaping it directly at the torch. For now the space is mainly set up for my own work; over time I would like to open it up step by step to other people interested in glass.",
  "studio.intro.de": "Meine Werkstatt in Kärnten ist der Ort, an dem aus Glasstäben und -röhren Schmuck, kleine Objekte, Experimente und Einzelstücke entstehen. Ich arbeite mit Borosilikatglas (COE 33), das in einer Sauerstoff-/Gasflamme auf Arbeitstemperatur gebracht und direkt am Brenner geformt wird. Im Moment ist der Platz vor allem für meine eigene Arbeit eingerichtet; langfristig möchte ich ihn Schritt für Schritt auch für andere Glasinteressierte öffnen.",

  "studio.material.eyebrow.en": "The material",
  "studio.material.eyebrow.de": "Das Material",
  "studio.material.title.en": "Why borosilicate glass?",
  "studio.material.title.de": "Warum Borosilikatglas?",
  "studio.material.text1.en": "Borosilicate glass is heat resistant, clear and precise to work with. That is exactly what makes it interesting to me: it can be shaped very deliberately at the torch while still leaving room for spontaneous decisions.",
  "studio.material.text1.de": "Borosilikatglas ist hitzebeständig, klar und präzise zu verarbeiten. Genau diese Eigenschaften machen es für mich so spannend: Es lässt sich am Brenner sehr kontrolliert formen und gleichzeitig bleibt genug Raum für spontane Entscheidungen.",
  "studio.material.text2.en": "Rods and tubes become shapes, colors and depth layer by layer. Some details are built on the surface, while others end up completely enclosed inside the glass.",
  "studio.material.text2.de": "Aus Stäben und Röhren entstehen Schicht für Schicht Formen, Farben und Tiefen. Manche Details werden außen aufgebaut, andere sitzen später vollständig im Glas.",

  "studio.process.eyebrow.en": "At the torch",
  "studio.process.eyebrow.de": "Am Brenner",
  "studio.process.title.en": "How glass becomes a one-off piece",
  "studio.process.title.de": "Wie aus Glas ein Einzelstück wird",
  "studio.process.text1.en": "In lampworking, the glass is heated directly in the flame, kept in constant motion and shaped step by step. Temperature, movement and timing determine how the material behaves.",
  "studio.process.text1.de": "Beim Lampworking wird das Glas direkt in der Flamme erhitzt, ständig bewegt und in kleinen Schritten geformt. Temperatur, Bewegung und Timing bestimmen dabei, wie sich das Material verhält.",
  "studio.process.text2.en": "I enjoy working with organic shapes, transparent depth, color and inclusions. Not every piece is planned from beginning to end — often the best idea develops while I am working.",
  "studio.process.text2.de": "Ich arbeite gerne mit organischen Formen, transparenten Tiefen, Farbe und Einbettungen. Nicht jedes Stück ist von Anfang bis Ende durchgeplant – oft entwickelt sich die beste Idee erst während der Arbeit.",

  "studio.gallery.eyebrow.en": "Inside the studio",
  "studio.gallery.eyebrow.de": "Einblicke",
  "studio.gallery.title.en": "From the studio",
  "studio.gallery.title.de": "Aus der Werkstatt",

  "studio.plans.eyebrow.en": "Studio time & workshops",
  "studio.plans.eyebrow.de": "Werkstattzeit & Workshops",
  "studio.plans.title.en": "The studio is meant to open up further",
  "studio.plans.title.de": "Die Werkstatt soll sich weiter öffnen",
  "studio.plans.intro.en": "Right now the studio is mainly my own workspace. Step by step, I would like it to also become a place where others can experience glass, learn, or work at the torch with their own experience.",
  "studio.plans.intro.de": "Im Moment ist die Werkstatt vor allem mein eigener Arbeitsplatz. Schritt für Schritt möchte ich daraus auch einen Ort machen, an dem andere Glas erleben, lernen oder mit eigener Erfahrung am Brenner arbeiten können.",

  "studio.card1.title.en": "Torch space",
  "studio.card1.title.de": "Brennerplatz",
  "studio.card1.text.en": "In the future I would like to offer a usable torch station for people who already have lampworking experience. The basic setup would include the torch, gas and oxygen, ventilation and the essential workshop equipment.",
  "studio.card1.text.de": "Geplant ist später ein nutzbarer Brennerplatz für Menschen, die bereits Erfahrung mit Lampworking haben. Brenner, Gas und Sauerstoff, Absaugung und grundlegende Werkstattausstattung sollen dabei vor Ort vorhanden sein.",
  "studio.card2.title.en": "Workshops",
  "studio.card2.title.de": "Workshops",
  "studio.card2.text.en": "For beginners or anyone who wants to focus on a specific technique, I would like to offer small workshops and individual sessions. Content and length depend on experience and goals — from first contact with material and flame to making a small glass piece of your own.",
  "studio.card2.text.de": "Für Einsteiger oder wenn du gezielt an einer Technik arbeiten möchtest, möchte ich kleine Workshops und individuelle Sessions anbieten. Inhalt und Umfang richten sich nach Erfahrung und Ziel – vom ersten Kontakt mit Material und Flamme bis zum eigenen kleinen Glasstück.",
  "studio.card3.title.en": "Exchange",
  "studio.card3.title.de": "Austausch",
  "studio.card3.text.en": "I do not want the workshop to be only a production space. It should also leave room for meeting other glassworkers, working together, sharing techniques and learning from one another.",
  "studio.card3.text.de": "Die Werkstatt soll nicht nur Produktionsort sein. Ich möchte auch Raum für Austausch mit anderen Glasleuten, gemeinsames Arbeiten, neue Techniken und gegenseitige Inspiration schaffen.",
  "studio.card4.title.en": "Studio space",
  "studio.card4.title.de": "Studioplatz",
  "studio.card4.text.en": "Do you already work with glass and need a place to work? There is enough room in my studio for another workspace. If you are looking for a regular or permanent studio spot, get in touch and we can see if it is a good fit.",
  "studio.card4.text.de": "Du arbeitest selbst mit Glas und suchst einen Platz zum Arbeiten? In meiner Werkstatt ist genug Raum für einen weiteren Arbeitsplatz. Wenn du einen regelmäßigen oder festen Studioplatz suchst, meld dich gerne – dann schauen wir gemeinsam, ob es passt.",
  "studio.vision.en": "I would rather let the workshop grow in a useful and safe way than rush into a large course program. That is why I am expanding the equipment, workstations and possibilities step by step while the space remains my own working studio as well.",
  "studio.vision.de": "Mir ist wichtiger, die Werkstatt sinnvoll und sicher wachsen zu lassen, als möglichst schnell ein großes Kursprogramm anzubieten. Deshalb baue ich Ausstattung, Arbeitsplätze und Möglichkeiten Schritt für Schritt aus – während der Raum weiterhin mein eigener Arbeitsplatz bleibt.",
  "studio.contact.eyebrow.en": "Workshop",
  "studio.contact.eyebrow.de": "Werkstatt",
  "studio.contact.title.en": "Curious about glass?",
  "studio.contact.title.de": "Neugierig auf Glas?",
  "studio.contact.text.en": "If you are interested in torch time, a workshop or a studio space, feel free to get in touch. We can work out the details personally.",
  "studio.contact.text.de": "Wenn du dich für Brennerzeit, einen Workshop oder einen Studioplatz interessierst, meld dich gerne. Alles Weitere können wir persönlich besprechen.",
  "studio.contact.button.en": "Send a message",
  "studio.contact.button.de": "Nachricht senden",

  "about.eyebrow.en": "Biography",
  "about.eyebrow.de": "Biografie",
  "about.p1.en": "Hey, my name is Florian Robatsch and I'm from Carinthia, Austria. Since 2019, I have been working with borosilicate glass and discovered my passion for lampworking – a special form of glasswork at the flame.",
  "about.p1.de": "Hey, mein Name ist Florian Robatsch und ich komme aus Kärnten, Österreich. Seit 2019 beschäftige ich mich mit Borosilikatglas und habe dabei meine Leidenschaft für das Lampworking entdeckt – eine besondere Form der Glasbearbeitung an der Flamme.",
  "about.p2.en": "What continues to fascinate me about it is the combination of precision and creativity. With a steady hand and a lot of heat, a hard and robust material can become something light, playful and often completely unexpected.",
  "about.p2.de": "Was mich daran bis heute fasziniert, ist die Verbindung aus Präzision und Kreativität. Mit ruhiger Hand und viel Hitze entsteht aus einem eigentlich harten und robusten Material etwas Leichtes, Verspieltes und oft ganz Unerwartetes.",
  "about.p3.en": "My work usually develops from a mixture of intuition, ideas and the joy of experimenting. I try not to plan every detail in advance, but instead leave some space for the glass and the process itself. I especially enjoy working with organic shapes, colors and details that give my pieces a natural and sometimes dreamlike character.",
  "about.p3.de": "Meine Arbeiten entstehen meist aus einer Mischung aus Intuition, Ideen und der Freude am Experimentieren. Ich versuche dabei nicht, jedes Detail im Voraus festzulegen, sondern lasse dem Glas und dem Entstehungsprozess auch etwas Raum. Besonders gerne arbeite ich mit organischen Formen, Farben und Details, die meinen Stücken einen natürlichen und manchmal verträumten Charakter geben.",
  "about.p4.en": "Not every piece develops exactly the way I originally imagined – and that is part of the process for me. I still find it fascinating to create something individual from glass that feels delicate and alive at the same time.",
  "about.p4.de": "Nicht jedes Stück entwickelt sich genau so, wie ich es ursprünglich geplant habe – und gerade das gehört für mich dazu. Es begeistert mich immer wieder, aus Glas etwas Eigenständiges zu erschaffen, das filigran und gleichzeitig lebendig wirkt.",
  "about.media.url": "/workshop/me2.jpg",
  "about.media.type": "image",

  "shop.eyebrow.en": "Shop",
  "shop.eyebrow.de": "Shop",
  "shop.title.en": "Available pieces",
  "shop.title.de": "Verfügbare Stücke",
  "shop.intro.en": "These pieces are currently available. Open a piece to see all details and send an inquiry from there.",
  "shop.intro.de": "Diese Stücke sind aktuell verfügbar. Öffne ein Stück für alle Details und stelle deine Anfrage direkt auf der Produktseite.",

  "gallery.eyebrow.en": "Gallery",
  "gallery.eyebrow.de": "Galerie",
  "gallery.intro.en": "A selection of jewelry, objects and experiments made in the workshop.",
  "gallery.intro.de": "Eine Auswahl an Schmuck, Objekten und Experimenten aus der Werkstatt.",

  "contact.eyebrow.en": "Contact",
  "contact.eyebrow.de": "Kontakt",
  "contact.title.en": "Get in touch.",
  "contact.title.de": "Meld dich.",
  "contact.intro.en": "Interested in a piece, a custom idea or the future studio setup? Send me a message here. Your inquiry is sent directly to me by email, and I can reply personally.",
  "contact.intro.de": "Du interessierst dich für ein Stück, eine eigene Idee oder die spätere Werkstatt-Nutzung? Schreib mir hier direkt. Deine Anfrage wird per E-Mail an mich geschickt und ich kann dir persönlich antworten.",
  "contact.listTitle.en": "You can ask me about",
  "contact.listTitle.de": "Du kannst mich fragen wegen",
  "contact.item1.en": "Available pieces",
  "contact.item1.de": "Verfügbaren Stücken",
  "contact.item2.en": "Custom ideas and commissions",
  "contact.item2.de": "Eigener Ideen und Anfragen",
  "contact.item3.en": "Future torch or studio time",
  "contact.item3.de": "Späterer Brenner- oder Werkstattzeit",
  "contact.item4.en": "Workshops",
  "contact.item4.de": "Workshops",
};

export function siteContentValue(
  content: SiteContentMap,
  key: string,
  fallback = "",
) {
  return Object.prototype.hasOwnProperty.call(content, key)
    ? content[key]
    : fallback;
}
