export type SiteContentMap = Record<string, string>;

export const SITE_CONTENT_DEFAULTS: SiteContentMap = {
  "home.hero.subtitle.en": "Borosilicate glass · Carinthia, Austria",
  "home.hero.subtitle.de": "Borosilikatglas · Kärnten, Österreich",
  "home.hero.text.en": "I’m Florian Robatsch, a glass artist from Carinthia. At the torch I turn borosilicate glass into one-of-a-kind jewelry, objects and whatever ideas happen to stick in my head.",
  "home.hero.text.de": "Ich bin Florian Robatsch, Glaskünstler aus Kärnten. Am Brenner entstehen aus Borosilikatglas handgemachte Unikate – Schmuck, Objekte und alles, was mir sonst noch durch den Kopf geht.",
  "home.hero.cta.en": "See the work",
  "home.hero.cta.de": "Arbeiten ansehen",
  "home.hero.media.url": "/workshop/me2.jpg",
  "home.hero.media.type": "image",

  "home.jewelry.eyebrow.en": "Jewelry",
  "home.jewelry.eyebrow.de": "Schmuck",
  "home.jewelry.title.en": "Glass to wear",
  "home.jewelry.title.de": "Glas zum Tragen",
  "home.jewelry.intro.en": "Handmade borosilicate glass pendants from Austria. Every piece is made individually at the torch and is one of a kind.",
  "home.jewelry.intro.de": "Handgemachte Anhänger aus Borosilikatglas aus Österreich. Jedes Stück entsteht einzeln am Brenner und ist ein Unikat.",

  "home.workshop.eyebrow.en": "Workshop",
  "home.workshop.eyebrow.de": "Werkstatt",
  "home.workshop.title.en": "At the torch",
  "home.workshop.title.de": "Am Brenner",
  "home.workshop.text.en": "I make each piece by hand from borosilicate glass in my workshop in Carinthia. Some start with a clear idea, others develop while I work.",
  "home.workshop.text.de": "In meiner Werkstatt in Kärnten fertige ich jedes Stück von Hand aus Borosilikatglas am Brenner. Manche Arbeiten sind vorher geplant, andere entwickeln sich erst beim Machen.",
  "home.workshop.main.url": "/workshop/me2.jpg",
  "home.workshop.main.type": "image",
  "home.workshop.media1.url": "/jewelry/Cobald5 x Opaldust Leaf.jpg",
  "home.workshop.media1.type": "image",
  "home.workshop.media2.url": "/workshop/me2.jpg",
  "home.workshop.media2.type": "image",

  "home.reviews.eyebrow.en": "Community",
  "home.reviews.eyebrow.de": "Community",
  "home.reviews.title.en": "What others say",
  "home.reviews.title.de": "Was andere sagen",
  "home.reviews.button.en": "View all",
  "home.reviews.button.de": "Alle ansehen",

  "home.studio.eyebrow.en": "Studio",
  "home.studio.eyebrow.de": "Werkstatt",
  "home.studio.title.en": "The workspace",
  "home.studio.title.de": "Der Arbeitsplatz",
  "home.studio.text.en": "A quick look at my workspace, the setup and my plans for future studio time and small sessions.",
  "home.studio.text.de": "Ein kleiner Einblick in meinen Arbeitsplatz, die Ausstattung und meine Pläne für spätere Werkstattzeit und kleine Sessions.",
  "home.studio.button.en": "Explore the studio",
  "home.studio.button.de": "Zum Studio",
  "home.studio.media.url": "/workshop/me2.jpg",
  "home.studio.media.type": "image",

  "studio.eyebrow.en": "Workspace",
  "studio.eyebrow.de": "Werkstatt",
  "studio.title.en": "The workshop",
  "studio.title.de": "Der Arbeitsplatz",
  "studio.intro.en": "I work with borosilicate glass in a small workshop in Austria. Right now I mainly use the space for my own pieces. Later I would like to make the space available to people interested in glass, whether they are just starting out or already have experience, and maybe offer small sessions.",
  "studio.intro.de": "Ich arbeite in einer kleinen Werkstatt in Österreich mit Borosilikatglas. Im Moment nutze ich den Platz hauptsächlich für meine eigenen Arbeiten. Später möchte ich den Raum auch für Menschen öffnen, die sich für Glas interessieren – egal ob Einsteiger oder mit Erfahrung – und kleine Sessions anbieten.",
  "studio.card1.title.en": "Torch rental",
  "studio.card1.title.de": "Brennervermietung",
  "studio.card1.text.en": "A properly equipped workstation for people with different levels of experience is something I would like to offer later.",
  "studio.card1.text.de": "Einen gut ausgestatteten Arbeitsplatz für Menschen mit unterschiedlichen Erfahrungsstufen würde ich später gerne anbieten.",
  "studio.card2.title.en": "Small workshops",
  "studio.card2.title.de": "Kleine Workshops",
  "studio.card2.text.en": "Small personal sessions may also become possible once the setup is ready.",
  "studio.card2.text.de": "Wenn alles passend eingerichtet ist, könnten auch kleine persönliche Sessions dazukommen.",
  "studio.card3.title.en": "Exchange",
  "studio.card3.title.de": "Austausch",
  "studio.card3.text.en": "I would like the space to be useful for meeting other glassworkers, sharing ideas and working together.",
  "studio.card3.text.de": "Der Platz soll auch für Austausch mit anderen Glasbläsern, Ideen und gemeinsames Arbeiten offen sein.",
  "studio.card4.title.en": "One-to-one sessions",
  "studio.card4.title.de": "Einzel-Sessions",
  "studio.card4.text.en": "Individual sessions could also be possible later, depending on time and setup.",
  "studio.card4.text.de": "Je nach Zeit und Ausstattung könnten später auch einzelne persönliche Sessions möglich sein.",
  "studio.vision.en": "The workshop is still developing. For now I use it for my own work and improve the setup step by step.",
  "studio.vision.de": "Die Werkstatt ist noch im Aufbau. Im Moment nutze ich sie für meine eigenen Arbeiten und verbessere die Ausstattung Schritt für Schritt.",
  "studio.contact.eyebrow.en": "Workshop",
  "studio.contact.eyebrow.de": "Werkstatt",
  "studio.contact.title.en": "Interested in the space?",
  "studio.contact.title.de": "Interesse am Platz?",
  "studio.contact.text.en": "If future torch rental, workshop time or a small session interests you, send me a message.",
  "studio.contact.text.de": "Wenn dich spätere Brennervermietung, Werkstattzeit oder eine kleine Session interessiert, schreib mir einfach.",
  "studio.contact.button.en": "Send a message",
  "studio.contact.button.de": "Nachricht senden",

  "about.eyebrow.en": "Biography",
  "about.eyebrow.de": "Biografie",
  "about.p1.en": "Hey, my name is Florian Robatsch and I'm from Carinthia, Austria. Since 2019, I have been working with borosilicate glass and discovered my passion for lampworking – a special form of glasswork at the flame.",
  "about.p1.de": "Hey, mein Name ist Florian Robatsch und ich komme aus Kärnten, Österreich. Seit 2019 beschäftige ich mich mit Borosilikatglas und habe dabei meine Leidenschaft für das Lampworking entdeckt – eine besondere Form der Glasbearbeitung an der Flamme.",
  "about.p2.en": "What continues to fascinate me about it is the combination of precision and creativity. With a steady hand and a lot of heat, a hard and robust material can become something light, playful and often completely unexpected.",
  "about.p2.de": "Was mich daran bis heute fasziniert, ist die Verbindung aus Präzision und Kreativität. Mit ruhiger Hand und viel Hitze entsteht aus einem eigentlich harten und robusten Material etwas Leichtes, Verspieltes und oft ganz Unerwartetes.",
  "about.p3.en": "My work usually develops from a mixture of intuition, ideas and the joy of experimenting. I try not to plan every detail in advance, but instead leave some space for the glass and the process itself. I especially enjoy working with organic shapes, colors and details that give my pieces a natural and sometimes dreamlike character.",
  "about.p3.de": "Meine Arbeiten entstehen meist aus einer Mischung aus Intuition, Ideen und der Freude am Experimentieren. Ich versuche dabei nicht, jedes Detail im Voraus festzulegen, sondern lasse dem Glas und dem Entstehungsprozess auch etwas Raum. Besonders gerne arbeite ich mit organischen Formen, Farben und Details, die meinen Stücken einen natürlichen und manchmal verträumten Charakter geben.",
  "about.p4.en": "Not every piece develops exactly the way I originally imagined – and that is part of the process for me. I still find it fascinating to create something individual from glass that feels delicate and alive at the same time.",
  "about.p4.de": "Nicht jedes Stück entwickelt sich genau so, wie ich es ursprünglich geplant habe – und gerade das gehört für mich dazu. Es begeistert mich immer wieder, aus Glas etwas Eigenständiges zu erschaffen, das filigran und gleichzeitig lebendig wirkt.",
  "about.media.url": "/workshop/me2.jpg",
  "about.media.type": "image",

  "shop.eyebrow.en": "Shop",
  "shop.eyebrow.de": "Shop",
  "shop.title.en": "Available pieces",
  "shop.title.de": "Verfügbare Stücke",
  "shop.intro.en": "These pieces are currently available. Open a piece to see all details and send an inquiry from there.",
  "shop.intro.de": "Diese Stücke sind aktuell verfügbar. Öffne ein Stück für alle Details und stelle deine Anfrage direkt auf der Produktseite.",

  "gallery.eyebrow.en": "Gallery",
  "gallery.eyebrow.de": "Galerie",
  "gallery.intro.en": "A selection of jewelry, objects and experiments made in the workshop.",
  "gallery.intro.de": "Eine Auswahl an Schmuck, Objekten und Experimenten aus der Werkstatt.",
  "gallery.media1.url": "/jewelry/Cobald5 x Opaldust Leaf.jpg",
  "gallery.media1.type": "image",
  "gallery.media2.url": "/jewelry/leaf2.jpg",
  "gallery.media2.type": "image",
  "gallery.media3.url": "/jewelry/AmberPurple Leaf STube (2).JPG",
  "gallery.media3.type": "image",
  "gallery.media4.url": "/jewelry/leaf4.jpg",
  "gallery.media4.type": "image",
  "gallery.media5.url": "/jewelry/leaf5.jpg",
  "gallery.media5.type": "image",
  "gallery.media6.url": "/jewelry/implo.jpg",
  "gallery.media6.type": "image",
  "gallery.media7.url": "/jewelry/Barkylett.JPG",
  "gallery.media7.type": "image",
  "gallery.media8.url": "/jewelry/Customer.JPG",
  "gallery.media8.type": "image",
  "gallery.media9.url": "/jewelry/IMG_2173 4.JPG",
  "gallery.media9.type": "image",
  "gallery.media10.url": "/jewelry/Mini Heart.JPG",
  "gallery.media10.type": "image",
};

export function siteContentValue(
  content: SiteContentMap,
  key: string,
  fallback = "",
) {
  return Object.prototype.hasOwnProperty.call(content, key)
    ? content[key]
    : fallback;
}
